### ISSUE TITLE
👷 Add to Homebrew-Core

### ISSUE THREAD

**Issue by bee-san** [TGotwig/homebrew-feroxbuster#5]
Hey Thomas! 👋

I saw your contribution to Feroxbuster, and as the RustScan core dev I thought I'd show you something helpful.

I spent a good while on the homebrew-core formula, so feel free to copy it for Feroxbuster. 

```ruby
class Rustscan < Formula
  desc "Modern Day Portscanner"
  homepage "https://github.com/rustscan/rustscan"
  url "https://github.com/RustScan/RustScan/archive/1.10.0.tar.gz"
  sha256 "63c387c645826107734eb10d45b0a540a69fb3a61e478593f515adce95bad530"
  license "GPL-3.0-or-later"

  bottle do
    cellar :any_skip_relocation
    sha256 "3f6072b555545a3efe33cc84aec3ba11c8110b038fe51cd1ec95be921e44fe16" => :catalina
    sha256 "29b494ff1b888b9cd2e94a61168236ccab5a2030a923efc490706301dcfe7bef" => :mojave
    sha256 "03b01fce247218e8dd5e60565199c61e4d458ab0d66f9952a2bbf158d04c9f0f" => :high_sierra
  end

  depends_on "rust" => :build
  depends_on "nmap"

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_no_match /panic/, shell_output("#{bin}/rustscan --greppable 127.0.0.1")
    assert_no_match /panic/, shell_output("#{bin}/rustscan --greppable 0.0.0.0")
  end
end
```

The tests run by grepping the output for the regex `/panic/`. So if the Rust program doesn't panic, it's a-okay!

Not sure on how much you know about core, so I'll share a few things:
* Project must be 30 days or older, and used by people (I can confirm that Ferox is, it's very popular in TryHackMe right now)
* You must follow [this very long process](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request)
* The format of the ruby file **must** be the same. One newline out of place and CI fails. If the order of items is different (license before sha256) and CI fails. They're very picky about this.

Other than that, good luck if you choose to contribute to core! Feel free to ping me in a PR if you need any more help :smile:

**Comment by tgotwig** [comment]
Hello again Bee! 🙋‍♂️

Thank you very much for this! I'll take a closer look soon 🕵️ btw nice title! Follows modern best-practices 🌟✨

I think to publish on Homebrew-Core it needs min. 30 forks, 30 watchers and 75 stars (at least for linuxbrew-core 😄).

**Comment by bee-san** [comment]
For what it's worth 👆 I found that submitting to homebrew-core made someone submit it to linuxbrew-core 💭 soooo my guess is that if you submit to one, someone will submit to both? 🤔

**Comment by tgotwig** [comment]
@bee-san Haha yeah that would explain why there are sometimes formulas for Linux but nothing about that inside the projects main readme! 😄

Hmmm maybe you know what the following error from the homebrew-core tests mean? What to do? 🤔

```
Formula/feroxbuster.rb#L8
https://github.com/epi052/feroxbuster/releases/download/v1.0.3/x86_64-macos-feroxbuster.tar.gz looks like a binary package, not a source archive; homebrew/core is source-only.
```

**Comment by bee-san** [comment]
Ah yes, that might be one of those ones that can be skipped. 😢 The homebrew-core tests are sometimes wrong, when I submitted my PR I had about ~3 checks that failed. One of them was really stupid ❓ "Version number in URL does not match version listed" despite the 2 versions were matching.

I think if you submit it, the core team will overlook it because it's clearly not a binary package 😇

**Comment by TGotwig** [comment]
@bee-san Ououou got the yellow card because of this one shitty ci-test of them 💩 next time better testing it with own ci before receiving the red one 🧪 btw Emojis are not allowed! 😨 Although the private formulas work with them 🤷‍♂️ Someone else can try with these guys there I'm out with this crap who needs official support anyway 😠🌋🌋🌋 But respect that your rustscan passed it! 😊🎖️

**Comment by tgotwig** [comment]
I think I will try again in one week or so after adding the build-stuff to the formula 🔧🙃

**Comment by tgotwig** [comment]
If somebody else like to continue on that, feel free to go for it 🙈🔧

**Comment by epi052** [comment]
@dnaka91 took care of this :tada:
